---
- name: Download the Splunk package (Debian/Ubuntu)
  ansible.builtin.get_url:
    url: "{{ splunk_forwarder_deb_url }}"
    dest: /tmp/{{ splunk_forwarder_deb_name }}
    checksum: "{{ splunk_forwarder_hash }}"
    mode: "0664"
  notify:
    - Enable Splunk Forwarder
    - Clear config for Cloning

- name: Install Splunk (Debian/Ubuntu)
  ansible.builtin.apt:
    deb: /tmp/{{ splunk_forwarder_deb_name }}
    state: present
  notify:
    - Enable Splunk Forwarder
    - Clear config for Cloning

- name: Install Python 3 as dependency
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    cache_valid_time: 3600

- name: Make sure awscli package is removed so we can install via pip
  ansible.builtin.apt:
    name:
      - awscli
      - python3-botocore
      - python3-boto3
    state: absent

- name: Install awscli as dependency via pip
  ansible.builtin.pip:
    name:
      - awscli
      - boto3
      - botocore
    state: present
