---
- name: Check if arm platform is requested for an unsupported Splunk Release Version
  fail: |
    msg="Exiting.  Splunk for ARM install via Package is only supported on release 9.0.2 or later"
  when: splunk_release is version('9.0.2', 'lt')

- name: Create Splunk group
  group:
    name: "{{ splunk_forwarder_group }}"
    gid: "{{ splunk_forwarder_gid }}"
    state: present
  tags: splunk_user
  when: splunk_create_user

- name: Create Splunk user
  user:
    name: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
    uid: "{{ splunk_forwarder_uid }}"
    state: present
  tags: splunk_user
  when: splunk_create_user

- name: Check if Splunk is installed
  stat:
    path: "{{ splunk_home }}/bin/splunk"
  register: splunk_installed

- name: Check Splunk Universal Forwarder Version Installed
  # -auth :{{ splunk_forwarder_admin_pass }}
  shell: |
      set -o pipefail
      if [ -f {{ splunk_home}}/bin/splunk ]; then
        {{ splunk_home}}/bin/splunk --accept-license --answer-yes -version |tail -1 |cut -d ' ' -f 4
      fi
  args:
    executable: /bin/bash
  register: splunk_version_check
  changed_when: splunk_version_check.stdout != splunk_release

- name: Install role package dependencies
  package:
    name: acl
    state: present

- name: Install Splunk Forwarder Client
  include_tasks: "{{ ansible_os_family }}.yml"
  when: splunk_version_check.stdout != splunk_release

- name: "Find all directories within $SPLUNK_HOME"
  find:
    path: "{{ splunk_home }}"
    file_type: any
    recurse: true
  register: splunk_contents
  when: not splunk_installed.stat.exists and splunk_forwarder_user != "splunk"

- name: "Recursively change ownership of $SPLUNK_HOME"
  file:
    path: "{{ item.path }}"
    owner: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
  loop: "{{ splunk_contents.files }}"
  when: not splunk_installed.stat.exists and splunk_forwarder_user != "splunk"

- name: Copy user seeds file
  template:
    src: user-seed.conf.j2
    dest: "{{ splunk_home}}/etc/system/local/user-seed.conf"
    mode: 0664
    backup: true
  when: splunk_forwarder_admin_user is defined and splunk_forwarder_admin_pass is defined
  tags: config_copy

- name: Create deploymentconf directory
  file:
    path: "{{ splunk_home}}/{{ splunk_deploymentconf_dir }}"
    state: directory
    mode: 0775
    owner: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
  when: splunk_forwarder_depl_server is defined
  tags: config_copy

- name: Copy deployment client file
  template:
    src: deploymentclient.conf.j2
    dest: "{{ splunk_home}}/{{ splunk_deploymentconf_dir }}/deploymentclient.conf"
    mode: 0664
    backup: true
  when: splunk_forwarder_depl_server is defined
  tags: config_copy

- name: Copy inputs file
  template:
    src: inputs.conf.j2
    dest: "{{ splunk_home}}/etc/system/local/inputs.conf"
    mode: 0664
    backup: true
  tags: config_copy

- name: Copy outputs file
  template:
    src: outputs.conf.j2
    dest: "{{ splunk_home}}/etc/system/local/outputs.conf"
    mode: 0664
    backup: true
  tags: config_copy

- name: Copy server file
  template:
    src: server.conf.j2
    dest: "{{ splunk_home}}/etc/system/local/server.conf"
    mode: 0664
    backup: true
  when: splunk_forwarder_output_use_tls
  tags: config_copy

- name: Set logfile permissions
  acl:
    path: "{{ item.path }}"
    entity: "{{ splunk_forwarder_user }}"
    state: present
    etype: user
    permissions: r
    recursive: true
  become: true
  with_items: "{{ splunk_forwarder_logs }}"
  when: splunk_set_log_permissions

- name: Accept Splunk License
  command: "{{ splunk_home}}/bin/splunk enable boot-start -systemd-managed 1 -user {{ splunk_forwarder_user }} -group {{ splunk_forwarder_group }} --accept-license --answer-yes --no-prompt"
  when: not splunk_installed.stat.exists
