---
- name: Enable Splunk Forwarder
  ansible.builtin.service:
    name: SplunkForwarder
    enabled: true
    state: started

- name: Clear config for Cloning
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk clone-prep-clear-config
  when: building_image
  tags:
    - skip_ansible_lint

- name: Restart Splunk Forwarder
  ansible.builtin.service:
    name: SplunkForwarder
    state: restarted
  listen: restart splunkforwarder

- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: reload daemon
