---
- name: Enable Splunk Forwarder
  ansible.builtin.service:
    name: SplunkForwarder
    enabled: true
    state: started

- name: Clear config for Cloning
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk clone-prep-clear-config
  when: building_image

- name: Restart Splunk Forwarder
  ansible.builtin.service:
    name: SplunkForwarder
    state: restarted
  listen: restart splunkforwarder
