---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    service_name: SplunkForwarder.service
  vars_files:
    - "../../defaults/main.yml"
  tasks:
    - name: Get the Groups
      getent:
        database: group

    - name: Get the Users
      getent:
        database: passwd

    - name: Assert Results
      assert:
        that:
          - getent_passwd.splunkfwd is defined
          - getent_group.splunkfwd is defined
        quiet: true

    - name: Gather service facts
      service_facts:

    - name: Print service facts
      debug:
        var: ansible_facts.services["{{ service_name }}"]

    - name: Assert splunk forwarder service is running
      assert:
        that: ansible_facts.services["{{ service_name }}"]["state"] == "running"
