---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    service_name: SplunkForwarder.service
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Get the Groups
      ansible.builtin.getent:
        database: group

    - name: Get the Users
      ansible.builtin.getent:
        database: passwd

    - name: Assert Results
      ansible.builtin.assert:
        that:
          - getent_passwd.splunkfwd is defined
          - getent_group.splunkfwd is defined
        quiet: true

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services["{{ service_name }}"]

    - name: Assert splunk forwarder service is running
      ansible.builtin.assert:
        that: ansible_facts.services["{{ service_name }}"]["state"] == "running"
